config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'youtube_vact/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "youtube_vact#index"
  resources :youtube_vact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/youtube_vact_controller.rb
class YoutubeVactController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/youtube_vact_helper.rb
module YoutubeVactHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoutubeVact</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("title_logo.png", class:"furima-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
       <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li> 
       <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
       <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
       <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_link.html.erb
<%= if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'btn'%>
<% end %>

<%=if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'btn'%>
<% end %>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/youtube_vact/index.html.erb
<%= render "shared/header" %>
<div class='main'>

</div>
<%= render "shared/footer" %>

app/views/youtube_vact/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="youtube_vact-show">
  <div class="youtube_vact-box">
    <h2 class="name">
      <%= @youtube_vact.youtube_vact_name %>
    </h2>
    <div class="youtube_vact-img-content">
      <%= image_tag @youtube_vact.image ,class:"youtube_vact-box-img" %>
       <% if @youtube_vact.purchase_management.present? %>
      <div class="sold-out">
        <span>Sold Out!!</span>
      </div>
      <%end%>
    </div>
    <div class="youtube_vact-price-box">
      <span class="youtube_vact-price">
       <%= "¥#{@youtube_vact.price}" %>
      </span>
      <span class="youtube_vact-postage">
        <%= @youtube_vact.charge.name %>
      </span>
    </div>
   
   
   <% if user_signed_in? && @youtube_vact.purchase_management.nil?%>
    <% if  current_user.id == @youtube_vact.user_id %>
    <%= link_to "商品の編集", edit_youtube_vact_path, method: :get, class: "youtube_vact-red-btn" %>
     <p class="or-text">or</p>
    <%= link_to "削除", youtube_vact_path, method: :delete, class:"youtube_vact-destroy" %>
   <% else %>
    <%= link_to "購入画面に進む", youtube_vact_purchases_path(@youtube_vact.id),class:"youtube_vact-red-btn"%>
    <%end%>
   <%end%>

    <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
  
    <div class="youtube_vact-explain-box">
      <span><%= @youtube_vact.introduction %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-youtube_vact">出品者</th>
          <td class="detail-value"><%= @youtube_vact.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-youtube_vact">カテゴリー</th>
          <td class="detail-value"><%= @youtube_vact.category.name %></td>
        </tr>
        <tr>
          <th class="detail-youtube_vact">商品の状態</th>
          <td class="detail-value"><%= @youtube_vact.condition.name %></td>
        </tr>
        <tr>
          <th class="detail-youtube_vact">配送料の負担</th>
          <td class="detail-value"><%= @youtube_vact.charge.name %></td>
        </tr>
        <tr>
          <th class="detail-youtube_vact">発送元の地域</th>
          <td class="detail-value"><%= @youtube_vact.area.name %></td>
        </tr>
        <tr>
          <th class="detail-youtube_vact">発送日の目安</th>
          <td class="detail-value"><%= @youtube_vact.deliveryTime.name %></td>
        </tr>
      </tbody>
    </table>

    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
 
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-youtube_vact-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-youtube_vact-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-youtube_vact"><%= @youtube_vact.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>